# Generated by Django 5.1.2 on 2024-10-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
