# Generated by Django 5.1.2 on 2024-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wish_list',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', help_text="If activated, it puts the book in wish list i.e book isn't purchased yet", max_length=9),
        ),
    ]
