# Generated by Django 5.1.2 on 2024-10-24 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_wish_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='wish_list',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', help_text="If enabled, it puts the book in wish list i.e book isn't purchased yet", max_length=9),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_book_author'),
        ),
    ]
